name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: TGP

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.VPS_PORT }} -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.VPS_PORT }} -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo âœ… SSH to VPS OK"

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e  # Dá»«ng script náº¿u cÃ³ lá»—i

            echo "âž¡ Pulling latest code"
            cd /var/www/seo-company-website
            git pull origin main

            echo "ðŸ“¦ Installing dependencies"
            npm install

            echo "ðŸ”¨ Building app"
            npm run build

            echo "ðŸš€ Restarting app with PM2"
            pm2 restart seo-company-website || pm2 start npm --name "seo-company-website" -- start -- -p 3001

            echo "ðŸ’¾ Saving PM2 state"
            pm2 save
          EOF
